apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
spec:
  selector:
    matchLabels:
      app: mysite
  replicas: 1
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: mysite
        image: https://github.com/FedeCB/DjangoSample/tree/main/mysite
        ports:
        - containerPort: 8080
